# Generated by Django 5.0.6 on 2024-07-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_delete_cliente_delete_mascota_delete_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroitem',
            name='nombre_producto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroitem',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.registro'),
        ),
        migrations.AlterField(
            model_name='registroitem',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crud.producto'),
        ),
    ]
