# Generated by Django 5.0.6 on 2024-07-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_registroitem_nombre_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='productos',
        ),
        migrations.AddField(
            model_name='registro',
            name='productos',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
