# Generated by Django 5.0.6 on 2024-07-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_remove_registro_productos_registro_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tamaño',
            field=models.CharField(choices=[('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Pequeño', 'Pequeño')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
