# Generated by Django 5.0.6 on 2024-07-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_producto_tamaño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Anillo', 'Anillo'), ('Aro', 'Aro'), ('Collar', 'Collar')], max_length=6),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='registro',
            name='productos',
        ),
        migrations.AlterField(
            model_name='registro',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registroitem',
            name='precio_producto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registroitem',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='registro',
            name='productos',
            field=models.ManyToManyField(through='crud.RegistroItem', to='crud.producto'),
        ),
    ]
