# Generated by Django 5.0.6 on 2024-07-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_alter_producto_categoria_alter_carrito_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
